'use client';
import {useState} from 'react';
import {createSharedTodo,createSharedCalendarEvent,updateSharedTodo, type ArrowTodo} from '@/lib/ravin';
export function PlanningControls({tasks,onChanged,onPlan}:{tasks:ArrowTodo[];onChanged:()=>Promise<void>;onPlan:()=>void}) {
 const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [kind,setKind]=useState('task');const [date,setDate]=useState(localDate());const [time,setTime]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [editing,setEditing]=useState<ArrowTodo|null>(null);
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(editing)await updateSharedTodo(editing.id,{title:title.trim(),due_on:date});else if(kind==='event')await createSharedCalendarEvent(title,date,time);else await createSharedTodo(title,date);setTitle('');setEditing(null);await onChanged();}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{setBusy(false);}}
 return <section className="planning-controls"><div className="planning-control-bar"><button type="button" onClick={()=>setOpen(!open)}>{open?'Close editor':'Add or edit'}</button><button type="button" onClick={onPlan}>Plan with RAVIN</button></div>{open&&<div className="planning-editor"><form onSubmit={save}><label>Type<select value={kind} disabled={!!editing} onChange={e=>setKind(e.target.value)}><option value="task">Task</option><option value="event">Calendar event</option></select></label><label>Title<input required maxLength={240} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs to happen?"/></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{kind==='event'&&<label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}<button type="submit" disabled={busy}>{busy?'Saving…':editing?'Save changes':'Add to ARROW'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setTitle('');}}>Cancel edit</button>}</form>{error&&<p role="alert">{error}</p>}<div className="planning-task-editor-list">{tasks.filter(t=>!t.completed).slice(0,50).map(task=><button key={task.id} type="button" onClick={()=>{setEditing(task);setKind('task');setTitle(task.title);setDate(task.due_on||localDate());}}><span>{task.title}</span><small>{task.due_on||'No date'} · Edit</small></button>)}</div></div>}</section>;
}
function localDate(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}
